### ISSUE TITLE
Publish on Maven

### ISSUE THREAD

**Issue by garronej** [jcputney/keycloak-theme-additional-info-extension#1]
Hello @jcputney,  

This extention if fantastic!  
It will be used in the next version of Keycloakify.  

Would you consider publishing on the Maven central repositort though?  
The GitHub Maven repository requires authentication even for download, I can't have all Keycloakify users fill up their GitHub PAT in `~/.m2/settings.xml`.  

Thanks a lot for opensourcing this!

**Comment by jcputney** [comment]
@garronej sure, never published anywhere, but I'll take a look

**Comment by garronej** [comment]
Hello @jcputney,  

I'm very glad to read your message.  
I was contemplating forking an publishing this under my name but it seems only right that you get the proper credit for your work.  

Not to pressure you but I'll release the next version of Keycloakify in a few days and I aready did the work of integrating this module. If you could find the time to publish it in the mean time that would be greatly appreciated.  

Here is a guide from GPT4: https://chat.openai.com/share/fd761f3f-95d8-4a32-9eb4-7dc2dc00cf41  

Thanks again for this. It will enable to have client side validation of the password policies!  


Best,

**Comment by jcputney** [comment]
@garronej well that was an adventure! Never realized just how difficult it is to get anything published to a public Maven repo. The latest version should be available shortly @ https://central.sonatype.com/artifact/dev.jcputney/keycloak-theme-additional-info-extension

**Comment by garronej** [comment]
@jcputney I'm truly grateful to you for taking the time to do this so quickly.
I apologize, I assumed it would be quick and easy but, as with most things in the Java stack, things are never that straightforward.
I'll be sure to mention that Keycloakify is using your module in the documentation regarding the user profile.

Thanks again,
