### ISSUE TITLE
Update in Keycloakify usage

### ISSUE THREAD

**Issue by garronej** [jcputney/keycloak-theme-additional-info-extension#3]
Hello @jcputney,  

I just wanted to send a quick message to tell you that `keycloak-theme-additional-info-extention` has been integrated in the Keycloakify v10 release candidate and pepoles are already levraging it to build cool things:  
 https://github.com/keycloakify/keycloakify/issues/593#issue-2424997273  
 
I also wanted to apologize for not giving you more credit in the Keycloakify documentation yet but be sure I'll properly acredit your work and link your repo in the Keycloakify v10 official release.  

Best

**Comment by jcputney** [comment]
@garronej awesome, thanks! Glad people are getting some use out of it!
